### ISSUE TITLE
potentially dropping metrics

### ISSUE THREAD

**Issue by jnation3406** [orionvm/potsdb#3]
I was experimenting with the library and noticed that occasionally metrics would never make it to my opentsdb instance. In looking through the source code I noticed it is sending with ***socket.send***. This function returns the number of bytes sent, but there is no code checking if it succeeded in sending all the bytes requested. Would it be safer to use ***socket.sendall*** instead? I believe this would attempt to send all the bytes requested, or throw an exception (which would lead you to retry sending the metric next time) if it failed or timed-out.

**Comment by mcclymont** [comment]
You're right about our socket.send usage. I think I will change it to sendall.

In the mean time, can you have a read through https://github.com/orionvm/potsdb/issues/2 and see if my comment helps?

**Comment by mcclymont** [comment]
socket.send has been changed to socket.sendall in v1.0.3 as per your suggestion, thanks.
